### ISSUE TITLE
Provide canonical EML record for doing the initial crosswalk

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig#3]
Or maybe 2 records.  Examine for completeness.

**Comment by gothub** [comment]
@mobb has suggested that [knb-lter-sbc.10](http://sbc.lternet.edu/cgi-bin/showDataset.cgi?docid=knb-lter-sbc.10) might be a good candidate. I has well described attributes for the dataTables and measurement units defined.

**Comment by mbjones** [comment]
Already tested against many EML records, so closing.
