### ISSUE TITLE
Mock up badge circles with progress indicators

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metadig#42]

**Comment by amoeba** [comment]
I threw up a place for these here: https://github.com/NCEAS/metadig/tree/master/mdqengine/docs/mockups/package-view. 

Feedback?
Other ideas?

**Comment by amoeba** [comment]
More mockups up. See links in bulleted list: https://github.com/NCEAS/metadig/tree/master/mdqengine/docs/mockups/package-view

**Comment by gothub** [comment]
Badge mockups were moved to https://github.com/NCEAS/metadig-engine/tree/master/docs/mockups
