### ISSUE TITLE
Extend EML2ISO transformation xslt

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig#5]
Needs to fully transform EML to ISO.  Be sure to not lose/drop detailed fields from entity/attribute sections.  Base on either the EML, LTER, or GBIF versions of this transform.

**Comment by yvanlebras** [comment]
with @earnaud we are working on [MetaShARK](https://github.com/earnaud/MetaShARK-v2) to try to "replace" Morpho and we are almost ready to try the integration of a conversion module to generate ISO19115 / ISO19110 files from EML. Don't know if you made improvement of this EML2ISO work but we will work on it probably during the next few weeks....

**Comment by mbjones** [comment]
This transform is no longer needed for MetaDIG, so closing. If it is desirable for other projects, let's create a new issue for it with details of what is needed.
