### ISSUE TITLE
Add metadata quality information to DataONE CN indexer

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig#83]
- [ ] determine what fields to index
- [ ] enter issue in DataONE redmine

**Comment by gothub** [comment]
The  metacat repo (trunk and soon to be 2.9.0 branch) contains modifications to the indexing files that will add metadata quality info to the Solr index when quality report documents are uploaded to a member node. The quality report formatId is "https://nceas.ucsb.edu/mdqe/v1#run". 

The metacat-index files will be added/updated to the DataONE CN component to affect this change:

src/main/resources/application-context-mdq.xml
src/main/resources/index-processor-context.xml

**Comment by mbjones** [comment]
Quality information ended up in its own SOLR index. CLosing as no longer needed.
