### ISSUE TITLE
Reorganize MetaDIG related git repos

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig#86]
Currently we have the following MetaDIG related repos:

https://github.com/NCEAS/mdqengine
https://github.com/NCEAS/mdq-webapp
https://github.com/NCEAS/metadig-r
https://github.com/NCEAS/metadig-py

Do we need an overhaul of the names of these repos/software components? We have discussed
this before, but can't find our discussion in notes or github issues.

**Comment by gothub** [comment]
How about the following changes?

https://github.com/NCEAS/mdqengine renamed to https://github.com/NCEAS/metadig-engine
https://github.com/NCEAS/mdq-webapp renamed to https://github.com/NCEAS/metadig-webapp
https://github.com/NCEAS/metadig-r stays the same
https://github.com/NCEAS/metadig-py stays the same

For the repos that change, components inside the repo will be changed appropriately, such as
the deliverable tar, war files, etc.

**Comment by amoeba** [comment]
Hey @gothub. I'd be okay with the change. This should help reduce confusion about what things are called.

**Comment by mbjones** [comment]
Sounds good to me too.  Don't forget we also have metadig/mdqengine as a
subfolder that contains engine docs, and those might be moved into the
metadig-engine repo.

Matt

**Comment by gothub** [comment]
@mbjones my github username does not have privs to rename any of these repos, as I don't
see 'Settings' tab for these repos. Could you either grant me privs or do the rename
for the mdqengine -> metadig-engine and mdq-webapp -> metadig-webapp?

Thanks!

**Comment by mbjones** [comment]
Done.  I renamed the two repositories to:

- `metadig-engine`
- `metadig-webapp`
